backend:
  name: github
  repo: billetfix/homepage
    
media_folder: static/img
public_folder: img


collections:
  
  - name: blog
    label: Blog
    folder: content/nav
    create: true
    fields:
      - { name: title, label: Title }
      - { name: path, label: Path }
      - { name: image, label: Image, widget: image, required: false }